# Generated by Django 5.1.2 on 2024-10-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodItem',
            new_name='FoodName',
        ),
    ]
